# Generated by Django 4.1.5 on 2023-02-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=14)),
                ("contactado", models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
