# Generated by Django 4.1.5 on 2023-02-08 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_info_date_alter_info_contactado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="date",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(
                    2023, 2, 8, 21, 27, 6, 98541, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
